config/routes.rb
Rails.application.routes.draw do

  # get 'publics/confirmations'
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, controllers: {
    sessions:      'admin/sessions',
    passwords:     'admin/passwords',
    registrations: 'admin/registrations'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.htmlscope module: :customers do
   #admin
  scope module: :public do
    root 'homes#top'
    # 商品
    resources :items, only: %i(show index)
    get 'genres/:id/genre_items' => 'items#genre_items'
    # 注文
    # post "orders/pre_create" => "orders#pre_create"
    post "orders/confirm" => "orders#confirm"
    resources :orders, only: [:new, :show, :create, :index]
    # 会員
    get "customers/unsubscribe" => "customers#unsubscribe"
    patch "customers/withdrawal" => "customers#withdrawal"
    resources :customers, only: [:show, :edit, :update, :destroy]
    # カート
    resources :cart_items, only: [:create, :index, :update, :destroy]
    delete 'cart_items' => 'cart_items#destroy_all'
    # 登録先住所
    # resources :shipping_addreses, only: %i(new show create edit update destroy)
  end
  #admin
  namespace :admin do
    root 'homes#top'
    resources :customers, only: [:show, :index, :edit, :update]
    resources :items,only: [:new, :show, :create, :edit, :index, :update]
    resources :genres, except: [:new, :show, :destroy]
    resources :orders, only: [:index, :show]
    get '/customer_datas/:id/orders' => 'orders#index', as: "customer_data_orders" # 会員詳細 => 注文履歴の表示データを変える用
    get '/yesterday/orders' => 'orders#index', as: "yesterday_orders" # TOP,本日製作分の注文数 => 注文履歴の表示データ用
    get '/today/orders' => 'orders#index', as: "today_orders" # TOP,本日受注した注文数 => 注文履歴の表示データ用
    patch '/orders/:id/order_status' => 'orders#order_status_update', as: "order_status" # 注文ステータスupdate
    patch '/orders/:id/item_status' => 'orders#item_status_update', as: "item_status" # 製作ステータスupdate
  end

  namespace :public do
  #customer
    root 'homes#top'

    get '/thanks' => 'homes#thanks' #サンクスページ
    get '/orders/confirm_order' => 'orders#confirm', as: 'orders_confirm' #購入確認画面への遷移
    post '/orders/pre_create' => 'orders#create_order' #購入確定のアクション
    post '/shipping_addreses' => 'orders#create_ship_address' #情報入力画面での配送先登録用のアクション
    delete '/cart_items' => 'cart_items#destroy_all' #カートアイテムを全て削除

    resources :shipping_addreses, except: [:index, :edit, :create, :update, :destroy]
    resources :cart_items, except: [:new, :show, :edit]
    resources :items, only: [:index, :show]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resources :genres, only: [:index] do
      resources :items, only: [:index]

    end
    resources :orders, except: [:edit, :update, :destroy]
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  def active_for_authentication?
    super && (is_deleted == false)
  end

  validates :last_name,  presence: true
  validates :first_name, presence: true
  validates :last_name_kana,  presence: true, format: {with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}
  validates :first_name_kana, presence: true, format: {with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}
  # カタカナ制限
  validates :telephone_number, presence: true, format: {with: /\A\d{10}$|^\d{11}\z/, message: '10桁か11桁の電話番号を入力してください。'}
  # ！！！電話番号の検証は現状空白のみ！！！
  validates :postal_code,  presence: true, format: {with: /\A\d{7}\z/}
   # 郵便番号のフォーマット指定 ハイフン無し７桁固定 Viewのフォーム設定
  validates :address, presence: true
  has_many :cart_items, dependent: :destroy
  has_many :ship_addresses, class_name: "ShippingAddre", dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

 
  def index
    @customers = Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path
    else
      flash[:customer_updated_error] = "会員情報が正常に保存されませんでした。"
      redirect_to edit_admin_customer_path(@customer)
    end
  end

  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_enabled)
  end
end

app/helpers/admins/customers_helper.rb
module Admins::CustomersHelper
end

app/helpers/publics/customers_helper.rb
module Publics::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container my-5">
  <div class="row">
    <h2>会員編集画面</h2>
  </div>

  <div class="row d-flex justify-content-center">
    <% if flash[:customer_updated_error] %>
      <span class="text-danger"><%= flash[:customer_updated_error] %></span>
    <% end %>
  </div>

    <div class="row mt-3 flex-column align-items-center">

      <%= form_for (@customer), url: admin_customer_path(@customer) do |f| %>

        <div class="form-group row">
          <%= f.label :会員id, class: "col-sm-4" %>
          <%= f.label @customer.id, class: "col-sm-8" %>
        </div>

        <div class="form-group row">
          <%= f.label :氏名, class: "col-sm-4" %>
          <%= f.text_field :last_name, class: "form-control col-sm-4" %>
          <%= f.text_field :first_name, class: "form-control col-sm-4" %>
        </div>

        <div class="form-group row">
          <%= f.label :フリガナ, class: "col-sm-4" %>
          <%= f.text_field :last_name_kana, class: "form-control col-sm-4" %>
          <%= f.text_field :first_name_kana, class: "form-control col-sm-4" %>
        </div>

        <div class="form-group row">
          <%= f.label :郵便番号, class: "col-sm-4" %>
          <%= f.text_field :postal_code, class: "form-control col-sm-8" %>
        </div>

        <div class="form-group row">
          <%= f.label :住所, class: "col-sm-4" %>
          <%= f.text_field :address, class: "form-control col-sm-8" %>
        </div>

        <div class="form-group row">
          <%= f.label :電話番号, class: "col-sm-4" %>
          <%= f.text_field :telephone_number, class: "form-control col-sm-8" %>
        </div>

        <div class="form-group row">
          <%= f.label :メールアドレス, class: "col-sm-4" %>
          <%= f.email_field :email, class: "form-control col-sm-8" %>
        </div>

        <div class="row">
          <%= f.label :会員ステータス, class: "ml-3" %>
          <div class="form-check ml-4">
            <%= f.radio_button :is_deleted, :true %>
            <%= f.label :is_deleted, "退会済み" %>
            <%= f.radio_button :is_deleted, :false %>
            <%= f.label :is_deleted, "有効会員" %>
          </div>
        </div>

        <div class="row">
          <%= f.submit "変更を保存する", class: "btn btn-primary mt-3 mx-auto" %>
        </div>

      <% end %>

  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container my-5">
  <div class="row">
    <h2>会員情報一覧</h2>
  </div>

  <div class="row mt-3">
    <div class="offset-sm-1 col-sm-10">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>会員ID</th>
          <th>氏名</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
        </tr>
      </thead>

      <tbody>
        <% @customers.each do |customer| %>
        <tr>
          <td><%= customer.id %></td>
          <td><%= link_to admin_customer_path(customer) do %>
              <%= customer.last_name %>
              <%= customer.first_name %>
              <% end %>
            </td>
          <td><%= customer.email %></td>
          <td><% if customer.is_deleted == true %>
              退会済み
              <% else %>
              有効会員
              <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
 </div>


  <div class="container">
    <div class="row">
    <div class="col-md-4 offset-md-4 py-2 mt-5">
    <%= paginate @customers %>
    </div>
    </div>
  </div> 

app/views/admin/customers/show.html.erb
<div class="container my-5">
  <div class="row">
    <h2>会員情報 詳細</h2>
  </div>

  <div class="row mt-3">
    <div class="offset-sm-1 col-sm-7">
      <table class="table table-borderless">
        <tbody>
          <tr>
            <td>顧客ID</td>
            <td><%= @customer.id %>
              <% if @customer.is_deleted == true %>
                <div class="bg-info d-inline text-white p-1 ml-3 rounded">
                  退会済み
                </div>
              <% else %>
                <div class="bg-warning d-inline text-white p-1 ml-3 rounded">
                  有効会員
                </div>
              <% end %>

            </div>
            </td>
          </tr>

          <tr>
            <td>氏名</td>
            <td><%= @customer.last_name %>
              <%= @customer.first_name %></td>
          </tr>

          <tr>
            <td>フリガナ</td>
            <td><%= @customer.last_name_kana %>
              <%= @customer.first_name_kana %></td>
          </tr>

          <tr>
            <td>郵便番号</td>
            <td><%= @customer.postal_code %></td>
          </tr>

          <tr>
            <td>住所</td>
            <td><%= @customer.address %></td>
          </tr>

          <tr>
            <td>電話番号</td>
            <td><%= @customer.telephone_number %></td>
          </tr>

          <tr>
            <td>メールアドレス</td>
            <td><%= @customer.email %></td>
          </tr>
        </tbody>
      </table>
    </div>

    <div class="col-sm-3 my-auto">
      <%= link_to "編集する", edit_admin_customer_path, class: "btn btn-primary" %>
      <%= link_to "注文履歴一覧を見る", admin_customer_data_orders_path, class: "btn btn-primary mt-5" %>
    </div>

  </div>
</div>

app/views/admin/customers/update.html.erb
<h1>Admins::Customers#update</h1>
<p>Find me in app/views/admins/customers/update.html.erb</p>