config/routes.rb
Rails.application.routes.draw do

  # get 'publics/confirmations'
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, controllers: {
    sessions:      'admin/sessions',
    passwords:     'admin/passwords',
    registrations: 'admin/registrations'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.htmlscope module: :customers do
   #admin
  scope module: :public do
    root 'homes#top'
    # 商品
    resources :items, only: %i(show index)
    get 'genres/:id/genre_items' => 'items#genre_items'
    # 注文
    # post "orders/pre_create" => "orders#pre_create"
    post "orders/confirm" => "orders#confirm"
    resources :orders, only: [:new, :show, :create, :index]
    # 会員
    get "customers/unsubscribe" => "customers#unsubscribe"
    patch "customers/withdrawal" => "customers#withdrawal"
    resources :customers, only: [:show, :edit, :update, :destroy]
    # カート
    resources :cart_items, only: [:create, :index, :update, :destroy]
    delete 'cart_items' => 'cart_items#destroy_all'
    # 登録先住所
    # resources :shipping_addreses, only: %i(new show create edit update destroy)
  end
  #admin
  namespace :admin do
    root 'homes#top'
    resources :customers, only: [:show, :index, :edit, :update]
    resources :items,only: [:new, :show, :create, :edit, :index, :update]
    resources :genres, except: [:new, :show, :destroy]
    resources :orders, only: [:index, :show]
    get '/customer_datas/:id/orders' => 'orders#index', as: "customer_data_orders" # 会員詳細 => 注文履歴の表示データを変える用
    get '/yesterday/orders' => 'orders#index', as: "yesterday_orders" # TOP,本日製作分の注文数 => 注文履歴の表示データ用
    get '/today/orders' => 'orders#index', as: "today_orders" # TOP,本日受注した注文数 => 注文履歴の表示データ用
    patch '/orders/:id/order_status' => 'orders#order_status_update', as: "order_status" # 注文ステータスupdate
    patch '/orders/:id/item_status' => 'orders#item_status_update', as: "item_status" # 製作ステータスupdate
  end

  namespace :public do
  #customer
    root 'homes#top'

    get '/thanks' => 'homes#thanks' #サンクスページ
    get '/orders/confirm_order' => 'orders#confirm', as: 'orders_confirm' #購入確認画面への遷移
    post '/orders/pre_create' => 'orders#create_order' #購入確定のアクション
    post '/shipping_addreses' => 'orders#create_ship_address' #情報入力画面での配送先登録用のアクション
    delete '/cart_items' => 'cart_items#destroy_all' #カートアイテムを全て削除

    resources :shipping_addreses, except: [:index, :edit, :create, :update, :destroy]
    resources :cart_items, except: [:new, :show, :edit]
    resources :items, only: [:index, :show]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resources :genres, only: [:index] do
      resources :items, only: [:index]

    end
    resources :orders, except: [:edit, :update, :destroy]
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
	has_many   :order_details, dependent: :destroy
	enum order_status: [:入金待ち, :入金確認, :製作中, :発送準備中, :発送済み]
	enum payment_method: { credit_card: 0, transfer: 1 }

  after_update do
    if self.order_status == "入金確認"
      self.order_details.each {|order_detail|
      order_detail.update(item_status: "製作待ち")
      }
    end
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def index
    if params[:id] # 会員詳細から来た場合
      @orders = Customer.find(params[:id]).orders.page(params[:page]).per(10)

    elsif request.fullpath.include? "today" # TOP本日受注分から来た場合
      @orders = Order.where(created_at:  Time.zone.now.all_day).page(params[:page]).per(10)

    elsif request.fullpath.include? "yesterday" # TOP本日製作分から来た場合
      @orders = Order.where(created_at: 1.day.ago.all_day).page(params[:page]).per(10)

    else
      @orders = Order.page(params[:page]).per(10)
    end
  end

  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details.all
    @items_total_price = calculate(@order)
  end

  def calculate(items_total_price) # 商品合計を算出するメソッド
    @items_total_price = 0
    @order_details.each {|order_detail|
      price = (order_detail.item_id * 1.1).floor
    sub_total_price = price * order_detail.amount
    @items_total_price += sub_total_price
    }
    return @items_total_price
  end

  def order_status_update
    order = Order.find(params[:id])
    order.update(order_params)
    # OrderModel after_update => 製作ステータスの自動変更
    redirect_to admin_order_path(order)
  end

  def item_status_update
    order_detail = OrderDetail.find(params[:id])
    order_detail.update(order_detail_params)
    # OrderDetailModel after_update => 注文ステータスの自動更新
    redirect_to admin_order_path(order_detail.order_id)
  end

  private
  def order_params
    params.require(:order).permit(:order_status)
  end

  def order_detail_params
    params.require(:order_detail).permit(:item_status)
  end
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/publics/orders_helper.rb
module Publics::OrdersHelper
end

app/views/admin/orders/index.html.erb
<div class="container my-5">
  <div class="row">
    <h2>注文一覧画面</h2>
  </div>

  <div class="row mt-5">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>購入日時</th>
          <th>購入者</th>
          <th>注文個数</th>
          <th>注文ステータス</th>
        </tr>
      </thead>

      <tbody>
        <% @orders.each do |order| %>
          <tr>
            <td><%= link_to order.created_at.strftime("%Y-%m-%d %H:%M"), admin_order_path(order) %></td>
            <!-- .strftime => created_atの表記を設定 -->
            <td><%= order.customer.last_name %>
              <%= order.customer.first_name %>
            </td>
            <td><%= order.order_details.sum(:amount) %></td>
            <td><%= order.order_status %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
 </div>

  <!-- ページネーション -->


  <div class="container">
    <div class="row">
     <div class="col-md-4 offset-md-4 py-2  mt-5">
      <%= paginate @orders %>
     </div>
    </div>
  </div>

app/views/admin/orders/show.html.erb
<div class="container my-5">
  <div class="row">
    <h2>注文詳細</h2>
  </div>

  <div class="row mt-3">
    <div class="col-sm-9">
      <table class="table table-borderless">

        <tbody>
          <tr>
            <td>購入者</td>
            <td>
              <%= link_to admin_customer_path(@order.customer) do %>
              <%= @order.customer.last_name %>
              <%= @order.customer.first_name %>
              <% end %>
            </td>
          </tr>

          <tr>
            <td>配送先</td>
            <% if @order.address.length <8 %>
            <% ship_address = ShipAddress.find(@order.address) %>
            <td><%= "〒" + ship_address.post_code + "  " + ship_address.address + "  " + ship_address.last_name + ship_address.first_name %></td>
            <% else %>
            <td><%= @order.address %></td>
            <% end %>
          </tr>

          <tr>
            <td>支払方法</td>
            <td><%= @order.payment_method %></td>
          </tr>

          <tr>
            <td>注文ステータス</td>
            <td><%= form_for (@order), url: admin_order_status_path(@order) do |f| %>
                <%= f.select :order_status, [["入金待ち", "入金待ち"], ["入金確認","入金確認"],["製作中","製作中"],["発送準備中","発送準備中"],["発送済み","発送済み"]], class: "form-control" %>
                <%= f.submit "更新", class: "btn btn-primary btn-sm" %>
                <% end %>
            </td>
          </tr>
        </tbody>

      </table>
    </div>
  </div>

  <div class="row mt-3">
    <div class="col-sm-9">

      <table class="table table-hover">
        <thead>
          <tr>
            <th>商品名</th>
            <th>単価(税込)</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
            <th colspan="1"></th>
          </tr>
        </thead>

        <% @order_details.each do |order_detail| %>
          <tbody>
            <tr>
              <td><%= order_detail.item_id %></td>
              <td><%= (order_detail.price * 1.1).floor %></td>
              <td><%= order_detail.amount %></td>
              <td><%= (order_detail.price * order_detail.amount * 1.1).floor %></td>
              <td>
                <%= form_for (order_detail), url: admin_item_status_path(order_detail, order_id: @order.id) do |f| %>
                  <%= f.select :item_status, [["着手不可", "着手不可"], ["製作待ち","製作待ち"], ["製作中","製作中"], ["製作完了","製作完了"]] %>
                  <%= f.submit "更新", class: "btn btn-primary btn-sm ml-3" %>
                <% end %>
                </td>
            </tr>
          </tbody>
        <% end %>
      </table>
    </div>

    <div class="col-sm-3 d-flex">
      <table class="table table-borderless align-self-end">
        <tbody>
          <tr class="border-bottom border-dark">
            <td>商品合計</td>
            <td><%= @items_total_price %></td>
          </tr>

          <tr class="border-bottom border-dark">
            <td>送料</td>
            <td><%= @order.postage %></td>
          </tr>

          <tr class="border-
          bottom border-dark">
            <td>請求合計金額</td>
            <td><%= @order.billing_amount %></td>
          </tr>
        </tbody>
      </table>

    </div>
  </div>
</div>

app/views/admin/orders/update.html.erb
<h1>Admins::Orders#update</h1>
<p>Find me in app/views/admins/orders/update.html.erb</p>