config/routes.rb
Rails.application.routes.draw do

  # get 'publics/confirmations'
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, controllers: {
    sessions:      'admin/sessions',
    passwords:     'admin/passwords',
    registrations: 'admin/registrations'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.htmlscope module: :customers do
   #admin
  scope module: :public do
    root 'homes#top'
    # 商品
    resources :items, only: %i(show index)
    get 'genres/:id/genre_items' => 'items#genre_items'
    # 注文
    # post "orders/pre_create" => "orders#pre_create"
    post "orders/confirm" => "orders#confirm"
    resources :orders, only: [:new, :show, :create, :index]
    # 会員
    get "customers/unsubscribe" => "customers#unsubscribe"
    patch "customers/withdrawal" => "customers#withdrawal"
    resources :customers, only: [:show, :edit, :update, :destroy]
    # カート
    resources :cart_items, only: [:create, :index, :update, :destroy]
    delete 'cart_items' => 'cart_items#destroy_all'
    # 登録先住所
    # resources :shipping_addreses, only: %i(new show create edit update destroy)
  end
  #admin
  namespace :admin do
    root 'homes#top'
    resources :customers, only: [:show, :index, :edit, :update]
    resources :items,only: [:new, :show, :create, :edit, :index, :update]
    resources :genres, except: [:new, :show, :destroy]
    resources :orders, only: [:index, :show]
    get '/customer_datas/:id/orders' => 'orders#index', as: "customer_data_orders" # 会員詳細 => 注文履歴の表示データを変える用
    get '/yesterday/orders' => 'orders#index', as: "yesterday_orders" # TOP,本日製作分の注文数 => 注文履歴の表示データ用
    get '/today/orders' => 'orders#index', as: "today_orders" # TOP,本日受注した注文数 => 注文履歴の表示データ用
    patch '/orders/:id/order_status' => 'orders#order_status_update', as: "order_status" # 注文ステータスupdate
    patch '/orders/:id/item_status' => 'orders#item_status_update', as: "item_status" # 製作ステータスupdate
  end

  namespace :public do
  #customer
    root 'homes#top'

    get '/thanks' => 'homes#thanks' #サンクスページ
    get '/orders/confirm_order' => 'orders#confirm', as: 'orders_confirm' #購入確認画面への遷移
    post '/orders/pre_create' => 'orders#create_order' #購入確定のアクション
    post '/shipping_addreses' => 'orders#create_ship_address' #情報入力画面での配送先登録用のアクション
    delete '/cart_items' => 'cart_items#destroy_all' #カートアイテムを全て削除

    resources :shipping_addreses, except: [:index, :edit, :create, :update, :destroy]
    resources :cart_items, except: [:new, :show, :edit]
    resources :items, only: [:index, :show]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resources :genres, only: [:index] do
      resources :items, only: [:index]

    end
    resources :orders, except: [:edit, :update, :destroy]
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :name, presence: true
	has_many :items

	# after_update do
	# 	if (is_enabled) == false
	# 		self.items.each {|item|
	# 			item.update(sale_status: "販売不可")
	# 		}
	# 	end
	# end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    if  @genre.save
      redirect_to admin_genres_path
    else
      flash[:genre_created_error] = "ジャンル名を入力してください。"
      redirect_to
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    genre = Genre.find(params[:id])
    if genre.update(genre_params)
      # Model:Genres.rb after_update => 無効にしたら関連商品の販売ステータスを販売不可に変更
      redirect_to admin_genres_path
    else
      flash[:genre_updated_error] = "ジャンル名を入力してください"
      redirect_to edit_admin_genre_path(genre)
    end
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/helpers/admins/genres_helper.rb
module Admins::GenresHelper
end

app/views/admin/genres/create.html.erb
<h1>Admins::Genres#create</h1>
<p>Find me in app/views/admins/genres/create.html.erb</p>

app/views/admin/genres/edit.html.erb
<div class="container my-5">
  <div class="row">
    <h2>ジャンル編集画面</h2>
  </div>

  <div class="row my-3 d-flex justify-content-center">
    <% if flash[:genre_updated_error] %>
      <span class="text-danger"><%= flash[:genre_updated_error] %></span>
    <% end %>
  </div>

  <div class="row flex-column align-items-center mt-3">
    <%= form_for(@genre, url: admin_genre_path) do |f| %>
      <div class="form-group row">
        <%= f.label :ジャンル名 %>
        <%= f.text_field :name, class: "form-control" %>
      </div>

      <div class="form-check">
        <%= f.radio_button :is_enabled, :true %>
        <%= f.label :is_enabled, "有効" %>
        <%= f.radio_button :is_enabled, :false %>
        <%= f.label :is_enabled, "無効" %>
      </div>

      <div class="row">
        <%= f.submit "更新する", class: "btn btn-primary mx-auto mt-3" %>
      </div>
    <% end %>
  </div>

</div>

app/views/admin/genres/update.html.erb
<h1>Admins::Genres#update</h1>
<p>Find me in app/views/admins/genres/update.html.erb</p>