config/routes.rb
Rails.application.routes.draw do

  # get 'publics/confirmations'
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, controllers: {
    sessions:      'admin/sessions',
    passwords:     'admin/passwords',
    registrations: 'admin/registrations'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.htmlscope module: :customers do
   #admin
  scope module: :public do
    root 'homes#top'
    # 商品
    resources :items, only: %i(show index)
    get 'genres/:id/genre_items' => 'items#genre_items'
    # 注文
    # post "orders/pre_create" => "orders#pre_create"
    post "orders/confirm" => "orders#confirm"
    resources :orders, only: [:new, :show, :create, :index]
    # 会員
    get "customers/unsubscribe" => "customers#unsubscribe"
    patch "customers/withdrawal" => "customers#withdrawal"
    resources :customers, only: [:show, :edit, :update, :destroy]
    # カート
    resources :cart_items, only: [:create, :index, :update, :destroy]
    delete 'cart_items' => 'cart_items#destroy_all'
    # 登録先住所
    # resources :shipping_addreses, only: %i(new show create edit update destroy)
  end
  #admin
  namespace :admin do
    root 'homes#top'
    resources :customers, only: [:show, :index, :edit, :update]
    resources :items,only: [:new, :show, :create, :edit, :index, :update]
    resources :genres, except: [:new, :show, :destroy]
    resources :orders, only: [:index, :show]
    get '/customer_datas/:id/orders' => 'orders#index', as: "customer_data_orders" # 会員詳細 => 注文履歴の表示データを変える用
    get '/yesterday/orders' => 'orders#index', as: "yesterday_orders" # TOP,本日製作分の注文数 => 注文履歴の表示データ用
    get '/today/orders' => 'orders#index', as: "today_orders" # TOP,本日受注した注文数 => 注文履歴の表示データ用
    patch '/orders/:id/order_status' => 'orders#order_status_update', as: "order_status" # 注文ステータスupdate
    patch '/orders/:id/item_status' => 'orders#item_status_update', as: "item_status" # 製作ステータスupdate
  end

  namespace :public do
  #customer
    root 'homes#top'

    get '/thanks' => 'homes#thanks' #サンクスページ
    get '/orders/confirm_order' => 'orders#confirm', as: 'orders_confirm' #購入確認画面への遷移
    post '/orders/pre_create' => 'orders#create_order' #購入確定のアクション
    post '/shipping_addreses' => 'orders#create_ship_address' #情報入力画面での配送先登録用のアクション
    delete '/cart_items' => 'cart_items#destroy_all' #カートアイテムを全て削除

    resources :shipping_addreses, except: [:index, :edit, :create, :update, :destroy]
    resources :cart_items, except: [:new, :show, :edit]
    resources :items, only: [:index, :show]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resources :genres, only: [:index] do
      resources :items, only: [:index]

    end
    resources :orders, except: [:edit, :update, :destroy]
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end
end

app/models/address.rb
class Address < ApplicationRecord


   validates :name, presence: true
   validates :postal_code,  presence: true, format: {with: /\A\d{7}\z/}
   # 郵便番号のフォーマット指定 ハイフン無し７桁固定 Viewのフォーム設定
   validates :address, presence: true
   belongs_to :customer
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  validates :amount, presence: true
   # 数量0以下に変更して保存されないように
   belongs_to :customer
   belongs_to :item

   def validate_into_cart
      cart_items = self.customer.cart_items
      if (amount) == nil
         return (false)
      elsif cart_items.any? {|cart_item| cart_item.item_id == (item_id)} == true
         return (false)
      else
        return (true)
      end
   end
   def sum_price
     item.price * amount
   end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  def active_for_authentication?
    super && (is_deleted == false)
  end

  validates :last_name,  presence: true
  validates :first_name, presence: true
  validates :last_name_kana,  presence: true, format: {with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}
  validates :first_name_kana, presence: true, format: {with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}
  # カタカナ制限
  validates :telephone_number, presence: true, format: {with: /\A\d{10}$|^\d{11}\z/, message: '10桁か11桁の電話番号を入力してください。'}
  # ！！！電話番号の検証は現状空白のみ！！！
  validates :postal_code,  presence: true, format: {with: /\A\d{7}\z/}
   # 郵便番号のフォーマット指定 ハイフン無し７桁固定 Viewのフォーム設定
  validates :address, presence: true
  has_many :cart_items, dependent: :destroy
  has_many :ship_addresses, class_name: "ShippingAddre", dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy

end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :name, presence: true
	has_many :items

	# after_update do
	# 	if (is_enabled) == false
	# 		self.items.each {|item|
	# 			item.update(sale_status: "販売不可")
	# 		}
	# 	end
	# end
end

app/models/item.rb
class Item < ApplicationRecord
	has_one_attached :image

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end


  validates :name, presence: true
	validates :introduction, presence: true
	validates :price, 		  presence: true
# 	validates :sale_status, presence: true
	# ！！with optionでまとめる！！
	has_many :cart_items, dependent: :destroy
# 	belongs_to :genre
	enum sale_status: [:販売可, :販売不可]
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
	has_many   :order_details, dependent: :destroy
	enum order_status: [:入金待ち, :入金確認, :製作中, :発送準備中, :発送済み]
	enum payment_method: { credit_card: 0, transfer: 1 }

  after_update do
    if self.order_status == "入金確認"
      self.order_details.each {|order_detail|
      order_detail.update(item_status: "製作待ち")
      }
    end
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
	enum item_status: [:着手不可, :製作待ち, :製作中, :製作完了]

  after_update do
    order_details = self.order.order_details
    if order_details.any? {|order_detail| order_detail.item_status == "製作中"} == true # 条件分岐：製作ステータスが1つでも製作中にだったら
      self.order.update(order_status: "製作中") # 注文ステータスを製作中に変更する
    elsif order_details.all? {|order_detail| order_detail.item_status == "製作完了"} == true # 条件分岐：製作ステータスが全て製作完了だったら
    self.order.update(order_status: "発送準備中") # 注文ステータスを発送準備中に変更する
    end
  end
end

app/models/shipping_addre.rb
class ShippingAddre < ApplicationRecord
  validates :last_name,  presence: true
   validates :first_name, presence: true
   validates :post_code,  presence: true, format: {with: /\A\d{7}\z/}
   # 郵便番号のフォーマット指定 ハイフン無し７桁固定 Viewのフォーム設定
   validates :address, presence: true
   belongs_to :customer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :configure_permitted_parameters, if: :devise_controller?

  # before_action :authenticate_customer!

  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :admin
      new_admin_session_path
    else
      root_path
    end
  end

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:is_enabled, :last_name, :first_name, :last_name_kana, :first_name_kana, :telephone_number, :postal_code, :address])
  end

end

app/helpers/admins/customers_helper.rb
module Admins::CustomersHelper
end

app/helpers/admins/genres_helper.rb
module Admins::GenresHelper
end

app/helpers/admins/homes_helper.rb
module Admins::HomesHelper
end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/publics/homes_helper.rb
module Publics::HomesHelper
end

app/helpers/publics/items_helper.rb
module Publics::ItemsHelper
end

app/helpers/publics/orders_helper.rb
module Publics::OrdersHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>
<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>
<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>
<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>
<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>
<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/_admin_header.html.erb
<nav class="navbar navbar-expand navbar-dark bg-dark navbar-fixed-top", style="background-color: #432c28;">
  <div class="container">
    <div class="row">
      <%= link_to "ながのcake管理者サイト", admin_root_path, class: "navbar-brand" %>
      <% if admin_signed_in? %>
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "商品一覧", admin_items_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "会員一覧",  admin_customers_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "注文履歴一覧", admin_orders_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "ジャンル一覧", admin_genres_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link" %>
          </li>
        </ul>

        <form class="form-inline">
          <input class="form-control-sm mr-sm-2" type="search" placeholder="検索...機能しないけど..." aria-label="検索...">
          <button type="submit" class="btn btn-outline-light btn-sm my-2 my-sm-0">検索</button>
        </form>
      <% end %>

    </div>
  </div>
</nav>

app/views/layouts/_customers_header.html.erb
<nav class="navbar navbar-expand navbar-dark navbar-fixed-top", style="background-color: #432c28;">
  <div class="container">

    <div class="navbar-header">
      <%= link_to "ながのcake", root_path, class: "navbar-brand" %>
    </div>

    <% if customer_signed_in? %>

      <span class="u h7 text-white strong">
        ようこそ！<%= current_customer.last_name %>
        <%= current_customer.first_name %>さん！
      </span>

      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "マイページ", customer_path(current_customer), class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "商品一覧", items_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "カート", cart_items_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "nav-link" %>
        </li>
      </ul>

    <% else %>

      <span class="u h7 text-white strong">
        ようこそ！ゲストさん！
      </span>

      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "会員登録", new_customer_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "ログイン", new_customer_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "商品一覧", items_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "店舗情報", "#", class: "nav-link" %>
        </li>
      </ul>

    <% end %>

    </div>
  </nav>

app/views/layouts/_error_message.html.erb
<% if model.errors.any? %>
  <div id="error-explanation" class="alert alert-danger">
  	 <h2><%= model.errors.count %> error prohibited this obj from being saved:</h2>
    <ul><% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag    'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'  %>
    <%= stylesheet_pack_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<!-- header デザイン分岐 -->
    <header class="header">
      <% if request.fullpath.include? "admin"  %>
        <%= render 'layouts/admin_header' %>
      <% else%>
        <%= render 'layouts/customers_header' %>
      <% end %>
    </header>

    <main>
      <%= yield %>
    </main>

<!-- footer デザイン分岐 -->
    <% if request.fullpath.include? "admin"  %>
      <footer class="footer text-white bg-dark">
    <% else%>
      <footer class="footer text-white", style="background-color: #432c28;">
    <% end %>

      <div class="container text-center mt-3">
    
      </div>
    </footer>


  </body>
</html>